2025-02-25 19:24:34.515 Uncaught app execution
Traceback (most recent call last):
  File "/home/samriddhi20/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/samriddhi20/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/mnt/c/Users/samri/persistent_queue_system/admin_console.py", line 7, in <module>
    jobs = db.get_all_jobs()
AttributeError: 'SQLiteQueue' object has no attribute 'get_all_jobs'
2025-02-25 19:24:39.227 Uncaught app execution
Traceback (most recent call last):
  File "/home/samriddhi20/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/samriddhi20/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/mnt/c/Users/samri/persistent_queue_system/admin_console.py", line 7, in <module>
    jobs = db.get_all_jobs()
AttributeError: 'SQLiteQueue' object has no attribute 'get_all_jobs'
2025-02-26 15:19:19.784 Uncaught app execution
Traceback (most recent call last):
  File "/home/samriddhi20/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
  File "/home/samriddhi20/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/mnt/c/Users/samri/persistent_queue_system/admin_console.py", line 7, in <module>
    jobs = db.get_all_jobs()
AttributeError: 'SQLiteQueue' object has no attribute 'get_all_jobs'
